on:
  push:
    branches:
      - master

name: 🚀 Deploy Node.js Backend on Push

jobs:
  web-deploy:
    name: 🎉 Deploy Node.js Backend
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 🔨 Install dependencies
        run: npm install

      - name: Log deployment details
        run: |
          echo "Deploying to server: ${{ secrets.GIT_CPANEL_SERVER }}"
          echo "Using protocol: ${{ secrets.GIT_CPANEL_PROTOCOL }}"

      - name: 📂 Sync backend files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 67.223.118.228 # Your CPanel server IP
          username: ${{ secrets.GIT_CPANEL_USER }}
          password: ${{ secrets.GIT_CPANEL_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_PROTOCOL }}
          local-dir: ./ # Sync the entire project folder
          server-dir: / # Path where your backend project should be deployed on your server
