on:
  push:
    branches:
      - master

name: 🚀 Deploy Node.js Backend on Push

jobs:
  web-deploy:
    name: 🎉 Deploy Node.js Backend
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: 🔨 Install dependencies
        run: npm install

      - name: Log deployment details
        run: |
          echo "Deploying to server: ${{ secrets.GIT_CPANEL_SERVER }}"
          echo "Using protocol: ${{ secrets.GIT_CPANEL_PROTOCOL }}"

      - name: 📂 Sync backend files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 67.223.118.228 # Your CPanel server IP
          username: ${{ secrets.GIT_CPANEL_USER }}
          password: ${{ secrets.GIT_CPANEL_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_PROTOCOL }}
          local-dir: ./* # Sync only the contents of the project folder
          server-dir: /home/omotqgku/kirastores-backend.omotoyecda.org/ # Deploy directly into this folder

      - name: 🔄 Restart server (if needed)
        run: |
          ssh ${{ secrets.GIT_CPANEL_USER }}@${{ secrets.GIT_CPANEL_SERVER }} 'pm2 restart kirastores-backend'

        env:
          GIT_CPANEL_SERVER: ${{ secrets.GIT_CPANEL_SERVER }}
